replicaCount: 1
image:
  repository: nexus-docker.ocp.hpb.tn.hr/todo-single
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: nexus-docker-auth
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

route:
  enabled: true

livenessProbe:
  httpGet:
    path: /todo/
    port: http
readinessProbe:
  httpGet:
    path: /todo/
    port: http

mysql:
  auth:
    database: todo
    username: todo
    password: todopassw0rd
  networkPolicy:
    enabled: false
  primary:
    pdb:
      create: false
  serviceAccount:
    create: false